In [45]:
import numpy as np

A = np.random.randint(1,10,(2,2,2,3))
print(A)
# From print output looks like columns are the RGB values 

B = [2,2,2]

[[[[6 1 8]
   [8 3 2]]

  [[1 4 4]
   [1 3 9]]]


 [[[4 2 9]
   [1 6 2]]

  [[9 2 7]
   [2 4 1]]]]


In [46]:
for i in range(3):
    C = np.dot(A[:,:,:,i],B[i])
print(C.shape)

print(C)

(2, 2, 2)
[[[16  4]
  [ 8 18]]

 [[18  4]
  [14  2]]]


In [51]:
# for i in range(3):
D = A[:,:,:,0]*2# + A[:,:,:,1] * B[1] + A[:,:,:,2] * B[2] 
print(D)
print(D.shape)

[[[12 16]
  [ 2  2]]

 [[ 8  2]
  [18  4]]]
(2, 2, 2)


In [54]:
# Extra test
import numpy.matlib 
import numpy as np 

a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
c = np.dot(a,b)

print(a*2)

print(a.shape)

print(c.shape)


[[2 4]
 [6 8]]
(2, 2)
(2, 2)
